# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultenv < Formula
  desc "A CLI tool for parsing and exporting vault driven .env files"
  homepage "mschmitt61"
  version "0.0.13"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mschmitt61/vaultenv/releases/download/v0.0.13/vaultenv_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a79975fd2faf9ccb809c040397c8f9f8315416f303339b8d60749969506d3b7b"

      def install
        bin.install "vaultenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mschmitt61/vaultenv/releases/download/v0.0.13/vaultenv_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "301cbcb983923c2a90c9e5d8a7bd1dcc009e43e086dcfd33e8c64388467a5136"

      def install
        bin.install "vaultenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mschmitt61/vaultenv/releases/download/v0.0.13/vaultenv_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "86d9b6f7a46d63b14a33dea75f108e851d378144660face52e6ac07ee028c8e4"

      def install
        bin.install "vaultenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mschmitt61/vaultenv/releases/download/v0.0.13/vaultenv_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9e2b4830acdcac951f8c17c3f3c75d90c397525f151eabb13716c26821311995"

      def install
        bin.install "vaultenv"
      end
    end
  end
end
