# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultenv < Formula
  desc ""
  homepage ""
  version "0.0.22"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mschmitt61/vaultenv/releases/download/v0.0.22/vaultenv_0.0.22_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "7d5e311a2c0ea76a4ed4e7281ecd6dedc298a0e2954adc97877b5185c3894247"

      def install
        bin.install "vaultenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mschmitt61/vaultenv/releases/download/v0.0.22/vaultenv_0.0.22_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d53fb041f83586f25ca19df06946576fdd042dac3b9404ef6151a3ee4e59cd78"

      def install
        bin.install "vaultenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mschmitt61/vaultenv/releases/download/v0.0.22/vaultenv_0.0.22_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5e0a504f471668e2c504f13409c3e8411eb8368d528f4c228463abf8551c8dff"

      def install
        bin.install "vaultenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mschmitt61/vaultenv/releases/download/v0.0.22/vaultenv_0.0.22_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e156c2d2f35ef54d2cde38831440f2264698c7b73753621a7654966cdb2c028b"

      def install
        bin.install "vaultenv"
      end
    end
  end
end
